FDY_DDF_CRNN:
  static_build_kernel_size: 3
  input_fdim: 128
  input_tdim: 626
  n_class: 10
  n_RNN_cell: 256
  n_RNN_layer: 2
  rec_dropout: 0
  attention: class                      # time / class
  
  n_input_ch: 1
  activation: cg
  conv_dropout: [ 0.5, 0.5]             #[conv, non_conv]
  se_ratio: [ 0.5, 0.25]                 #[channel, spatial_attention]
  kernel: [ 3, 3, 3, 3, 3, 3, 3 ]
  pad: [ 1, 1, 1, 1, 1, 1, 1 ]
  stride: [ 1, 1, 1, 1, 1, 1, 1 ]
  n_filt: [ 32, 64, 128, 256, 256, 256, 256 ]
  f_dim: [ 128, 64, 32, 16, 8, 4, 2, 1]
  pooling: [ [ 2, 2 ], [ 2, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ] ]
  DY_layers: [ 0, 1, 1, 1, 1, 1, 1 ]

  temperature: 31
  spatial_kernel_type: "build_F"                      # build_F or build_T or buld_square
  pool_dim: time                       # leave time: "freq", pool time "time", pool both: "both"